### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by mexikoedi** [Blechkanne/ttt2_the_soap#1]
When the soap is placed it throws a script error.
Tested with newest TTT2 Steam Workshop version and with this collection: https://steamcommunity.com/sharedfiles/filedetails/?id=1822673195

```
Error:
[[TTT2] The Soap] lua/weapons/weapon_soap.lua:83: attempt to index global 'cleanup' (a function value)
  1. unknown - lua/weapons/weapon_soap.lua:83
 ```

**Comment by Blechkanne** [comment]
I could not recreate your problem. Used TTT2 Version 0.12.3b + TTT2_Soap
![image](https://github.com/Blechkanne/ttt2_the_soap/assets/104766480/789c5b52-371e-4c7d-be45-ab95ef81fe89)

Might be something with a different addon?

**Comment by mexikoedi** [comment]
> I could not recreate your problem. Used TTT2 Version 0.12.3b + TTT2_Soap
> ![image](https://github.com/Blechkanne/ttt2_the_soap/assets/104766480/789c5b52-371e-4c7d-be45-ab95ef81fe89)
> 
> Might be something with a different addon?

Hmm, ok.
I will test it without any addons next time and report back but I didn't add any new addons and it worked before.
Weird.

**Comment by mexikoedi** [comment]
So I tested it on a P2P server and had no issues. I even enabled all my addons and everything worked.
Maybe some cache issue or something else on my dedicated server?
I close this issue because this addon is working as intended.

**Comment by mexikoedi** [comment]
The cache was not the issue. It was a different addon.
Explosive Crossbow uses "cleanup" as a global function.
Solved it on my end.
